# Generated by Django 6.0.1 on 2026-03-04 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
