# Generated by Django 6.0.1 on 2026-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_model',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
