# Generated by Django 6.0.1 on 2026-03-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_model',
            new_name='Transaction_history_model',
        ),
    ]
