# Generated by Django 6.0.1 on 2026-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_model',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
