# Generated by Django 6.0.3 on 2026-03-09 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_expense_model_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_model',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
