# Generated by Django 6.0.1 on 2026-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_income_model_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('expense_payment_method', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
