# Generated by Django 6.0.3 on 2026-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_income_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_model',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income_model',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
