# Generated by Django 6.0.1 on 2026-02-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_expense_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensereport_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
