# Generated by Django 6.0.1 on 2026-03-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_expensereport_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_model',
            name='date',
            field=models.DateField(),
        ),
    ]
