# Generated by Django 6.0.3 on 2026-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_expense_model_notes_alter_income_model_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_model',
            name='date',
            field=models.DateField(),
        ),
    ]
