# Generated by Django 6.0.1 on 2026-03-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_expense_model_date'),
        ('transactions', '0007_alter_expense_model_id_alter_expensereport_model_id_and_more'),
    ]

    operations = [
    ]
