# Generated by Django 6.0.1 on 2026-03-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_merge_20260303_1530'),
        ('transactions', '0009_alter_expense_model_id_alter_expensereport_model_id_and_more'),
    ]

    operations = [
    ]
