# Generated by Django 6.0.1 on 2026-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_alter_investmentplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
