# Generated by Django 5.2.4 on 2026-03-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMI', '0002_alter_emimanager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimanager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
