# Generated by Django 6.0.1 on 2026-03-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMI', '0005_alter_emimanager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimanager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
